/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Amelia Wolf
 */
import client.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class VistaCliente extends javax.swing.JFrame {

    private Client cliente;
    private JFileChooser fileChooser;

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblIntro = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        lblDirec = new javax.swing.JLabel();
        btnAjustar = new javax.swing.JButton();
        lblSelec = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        txtDirectorio = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaInfo = new javax.swing.JTextArea();
        lblSelec1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtArchi = new javax.swing.JTextField();
        btnBuscarArchi = new javax.swing.JButton();
        btnDescargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitulo.setText("---- CLIENTE 0 ---- ");

        lblIntro.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblIntro.setText("/ / / Introduzca parámetros del cliente / / / ");

        lblPuerto.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lblPuerto.setText("Puerto:");

        lblDirec.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lblDirec.setText("Directorio:");

        btnAjustar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnAjustar.setText("AJUSTAR AGENTE");
        btnAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustarActionPerformed(evt);
            }
        });

        lblSelec.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSelec.setText("/ / / Selecciona el archivo que quieres descargar / / / ");

        txtDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorioActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblInfo.setText("* * * INFORMACIÓN DE EJECUCIÓN * * *");

        txtaInfo.setColumns(20);
        txtaInfo.setRows(5);
        jScrollPane1.setViewportView(txtaInfo);

        lblSelec1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSelec1.setText("Busca el fichero y pulse DESCARGAR para comenzar");

        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel3.setText("Buscar Archivo:");

        btnBuscarArchi.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnBuscarArchi.setText("Buscar");

        btnDescargar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnDescargar.setText("DESCARGAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAjustar)
                    .addComponent(lblSelec)
                    .addComponent(lblInfo)
                    .addComponent(lblTitulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArchi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarArchi))
                    .addComponent(btnDescargar)
                    .addComponent(lblSelec1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPuerto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblDirec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblIntro)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuerto)
                    .addComponent(lblDirec)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(btnAjustar)
                .addGap(37, 37, 37)
                .addComponent(lblSelec)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtArchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarArchi))
                .addGap(18, 18, 18)
                .addComponent(btnDescargar)
                .addGap(31, 31, 31)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelec1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustarActionPerformed
        cliente = new Client(this);
        try {
            cliente.conectarClient(txtDirectorio.getText(), txtPuerto.getText());
        } catch (IOException ex) {
            Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjustarActionPerformed

    private void txtDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            txtDirectorio.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    
    public void entrada(String msg) {
        txtaInfo.append(msg + "\n");
        txtaInfo.setCaretPosition(txtaInfo.getDocument().getLength());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarArchi;
    private javax.swing.JButton btnDescargar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDirec;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblIntro;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblSelec;
    private javax.swing.JLabel lblSelec1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtArchi;
    private javax.swing.JTextField txtDirectorio;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextArea txtaInfo;
    // End of variables declaration//GEN-END:variables
}
